### ISSUE TITLE
sveltejs/kit beta: t is not a function

### ISSUE THREAD

**Issue by tw1t611** [kaisermann/svelte-i18n#134]
**Describe the bug**
The plugin throws this error:
```bash
TypeError: t is not a function
    at /home/user/Projects/ari-motors-v2/node_modules/svelte-i18n/dist/runtime.cjs.js:1:1039
    at Array.map (<anonymous>)
    at w (/home/user/Projects/ari-motors-v2/node_modules/svelte-i18n/dist/runtime.cjs.js:1:968)
    at /home/user/Projects/ari-motors-v2/node_modules/svelte-i18n/dist/runtime.cjs.js:1:1314
    at Array.map (<anonymous>)
    at b (/home/user/Projects/ari-motors-v2/node_modules/svelte-i18n/dist/runtime.cjs.js:1:1300)
    at Object.L.set (/home/user/Projects/ari-motors-v2/node_modules/svelte-i18n/dist/runtime.cjs.js:16:1835)
    at Proxy.exports.init (/home/user/Projects/ari-motors-v2/node_modules/svelte-i18n/dist/runtime.cjs.js:16:5682)
    at $layout.svelte:30:6
    at Object.$$render (/home/user/Projects/ari-motors-v2/node_modules/svelte/internal/index.js:1369:22)
```

**To Reproduce**
Add the following code to a newly created project:

$layout.svelte
```js
  import {
    register,
    init,
    getLocaleFromPathname,
    getLocaleFromNavigator,
    locale,
    waitLocale,
  } from "svelte-i18n";
  import de from "./_lang/de.json";

  register("de", de);

  init({
    initialLocale: "de
  })
```

/_lang/de.json
```js
{}
```

**Expected behavior**
Should load the locale

Furthermore, could you provide some info on how to get it working, if you get another solution.
I'd like to set up my locales without even creating the json files, because the translations will be pulled from a headless cms at build time.

**Comment by jakobbouchard** [comment]
I've had issues like you, which I've half-fixed. Your specific issue, you can probably fix it by doing this in a `<script context="module">` tag.
```js
	import { waitLocale } from 'svelte-i18n'

	export async function load() {
		// awaits for 'en' loaders
		return waitLocale()
	}
```

However, I've had a couple of other issues, which I listed [here](https://github.com/kaisermann/svelte-i18n/issues/139)

**Comment by tw1t611** [comment]
Ty, got it working for now. I will close this, since you have an other issue for related bugs.
