### ISSUE TITLE
(Sapper i18n) Error: Cannot find module 'svelte/store' breaks deployment

### ISSUE THREAD

**Issue by il-picchio** [kaisermann/svelte-i18n#136]
BUG:
- svelte-18n: 3.3.7
- sapper: 0.29.1
- Rollup
- Cloud deployment

After installing svelte-i18n through npm, the deployment on the server (scalingo) fails. Build succeed but the deployment fails when the app needs to boot.
It's not needed to setup library or so, just install it. 

Using "npm run dev" everything works fine.

app@0.0.1 start /app

node **sapper**/build

Starting server on port 24566

internal/modules/cjs/loader.js:818

throw err;
^
 Error: Cannot find module 'svelte/store'

Require stack:
/app/node_modules/svelte-i18n/dist/runtime.cjs.js
/app/**sapper**/build/server/server.js
/app/**sapper**/build/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object. (/app/node_modules/svelte-i18n/dist/runtime.cjs.js:1:75)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
 at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19) {
code: 'MODULE_NOT_FOUND',
requireStack: \[
 '/app/node_modules/svelte-i18n/dist/runtime.cjs.js',
 '/app/**sapper**/build/server/server.js',
 '/app/**sapper**/build/index.js'
 \]
}

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.1 start: `node __sapper__/build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /app/.npm/_logs/2021-03-16T16_57_03_501Z-debug.log

**Comment by il-picchio** [comment]
Update: the problem is only related to an issue of the cloud provider.
Contacting the cloud provider fixed the problem without any fix in the code.

**Comment by onuroo** [comment]
<img width="351" alt="Screen Shot 2021-08-14 at 12 26 19" src="https://user-images.githubusercontent.com/5569462/129441461-87931f2b-0478-41ad-aef2-0c4ffab37dfc.png">

You have to add engine field that included node version ( e.g. 15.12.0 ).
