### ISSUE TITLE
ERR_INVALID_URL when loading en.json

### ISSUE THREAD

**Issue by ApplePie420** [kaisermann/svelte-i18n#161]
**Describe the bug**
When i run the server with `npm run dev` and refresh the page in browser, server crashes with following:

**Logs**
```
D:\My Files\Programovanie\Node\jsLearning>npm run dev

> jslearning@0.0.1 dev
> svelte-kit dev


  vite v2.5.10 dev server running at:

  > Local: http://localhost:3000/    
  > Network: use `--host` to expose  

  SvelteKit v1.0.0-next.174

  network: not exposed
  network: not exposed
  network: not exposed
  network: not exposed
  network: not exposed
  local:   http://localhost:3000

  Use --host to expose server to other devices on this network


/lang/en.json
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new Request (file:///D:/My%20Files/Programovanie/Node/jsLearning/node_modules/@sveltejs/kit/dist/install-fetch.js:1244:16)
    at file:///D:/My%20Files/Programovanie/Node/jsLearning/node_modules/@sveltejs/kit/dist/install-fetch.js:1453:19
    at new Promise (<anonymous>)
    at fetch (file:///D:/My%20Files/Programovanie/Node/jsLearning/node_modules/@sveltejs/kit/dist/install-fetch.js:1451:9)
    at Module.setupI18n (/src/services/i18n.js:16:12)
    at eval (/src/routes/index.svelte:39:26)
    at Object.$$render (D:\My Files\Programovanie\Node\jsLearning\node_modules\svelte\internal\index.js:1684:22) {
  input: '/lang/en.json',
  code: 'ERR_INVALID_URL'
}
```

**To Reproduce**
Folder structure:
```
./
- public/lang/en.json
- src
-- components/langSwitcher.svelte
-- routes/index.svelte
-- services/i18n.js
```

i18n.js
```js
import { derived } from "svelte/store";
import { dictionary, locale, _ } from "svelte-i18n";

const MESSAGE_FILE_URL_TEMPLATE = '/lang/{locale}.json';

let cachedLocale;

function setupI18n({ withLocale: _locale } = { withLocale: 'en' }) {
    const messsagesFileUrl = MESSAGE_FILE_URL_TEMPLATE.replace('{locale}', _locale);
    console.log(messsagesFileUrl);

    return fetch(messsagesFileUrl)
        .then(response => response.json())
        .then((messages) => {
            dictionary.set({ [_locale]: messages });
            cachedLocale = _locale;
            locale.set(_locale);
        });
}

const isLocaleLoaded = derived(locale, $locale => typeof $locale === 'string');

export { _, locale, setupI18n, isLocaleLoaded };
```

index.svelte
```svelte
<script>
	import { _, setupI18n, isLocaleLoaded, locale } from '../services/i18n';

	import LocaleSelector from "../components/languageSwitcher.svelte";

	$: if (!$isLocaleLoaded) {
        setupI18n({ withLocale: 'en' });
    }
</script>


{#if $isLocaleLoaded}
	<LocaleSelector value={$locale} on:locale-changed={e => setupI18n({ withLocale: e.detail }) } />

	<p>
		{$_("my_account")}
	</p>
{:else}
    <p>Loading...</p>
{/if}
```

languageSwitcher.svelte
```svelte
<script>
    import { createEventDispatcher } from 'svelte';
    export let value = 'en';
    const dispatch = createEventDispatcher();
    function handleLocaleChange(event) {
        event.preventDefault();
        dispatch('locale-changed', event.target.value);
    }
</script>

<div class="locale-selector">
    <div class="select">
        <select value={value} on:change={handleLocaleChange}>
            <option value="en">EN</option>
            <option value="cz">CZ</option>
        </select>
    </div>
</div>
```

**Expected behavior**
Blank webpage with english text and a language switcher that allows me to swtich from english to czech language

**Information about your project:**
Firefox 92.0 64-bit, node 16.10.0
Windows 10
svelte-i18n 3.3.10

**Additional context**
Funny thing is, on my MacOS laptot, the server will run. When I refresh the page, it will throw out the exact same error, but server will continue to work (that's why I overlooked it initially). But on Windows, it crashes and nothing works. I have tried moving the locale files to different places, even to the exact same folder where `i18n.js` is, but nothing works.

**Comment by ApplePie420** [comment]
okay nevermid, I had to move the stuff to public folder and explicitly set `http://localhost:3000/lang/{lang}.json` in the fetch, because idk javascript. Closing.
