### ISSUE TITLE
[!] CLI Error: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by jhewt** [kaisermann/svelte-i18n#46]
**Describe the bug**
Trying to run the CLI for extracting, always returns Unexpected token u in JSON at position 0

**To Reproduce**
Simply run: ` yarn run svelte-i18n extract src/**/*.svelte `

**Expected behavior**
Create the expected json file

**Stacktraces**
<details>
  <summary>Stack trace</summary>

```bash
✗ yarn run svelte-i18n extract src/**/*.svelte 
yarn run v1.17.0
$ /Users/josesachs/sapper-proj/node_modules/.bin/svelte-i18n extract src/components/Checkbox.svelte src/components/HotelSlides.svelte src/components/InputBox.svelte src/components/blocks/About.svelte src/components/blocks/CityHero.svelte src/components/blocks/FadeShow.svelte src/components/blocks/HotelSlides.svelte src/components/blocks/Hotels.svelte src/components/blocks/PromoSlide.svelte src/components/blocks/Promos.svelte src/components/blocks/ReservationDetail.svelte src/components/blocks/ResultInfo.svelte src/components/blocks/RoomList.svelte src/components/blocks/RoomListMobile.svelte src/components/blocks/SearchBox.svelte src/components/blocks/ServiceBox.svelte src/components/blocks/Services.svelte src/components/blocks/SlideShow.svelte src/components/blocks/StepsBox.svelte src/components/cards/PromoHotel.svelte src/components/cards/RoomResult.svelte src/components/dropdowns/Calendar.svelte src/components/dropdowns/CalendarDropdown.svelte src/components/dropdowns/CurrencyDropdown.svelte src/components/dropdowns/Dropdown.svelte src/components/dropdowns/DropdownLabeless.svelte src/components/dropdowns/Month.svelte src/components/dropdowns/RoomsDropdown.svelte src/components/dropdowns/SelectDropdown.svelte src/components/emails/reservation.svelte src/components/layout/Contact.svelte src/components/layout/FloatingIcons.svelte src/components/layout/Footer.svelte src/components/layout/Header.svelte src/components/layout/Menu.svelte src/components/layout/Newsletter.svelte src/components/layout/OuterHeader.svelte src/components/layout/ProgressBar.svelte src/node_modules/@sapper/internal/App.svelte src/node_modules/@sapper/internal/error.svelte src/node_modules/@sapper/internal/layout.svelte src/routes/[city]/[hotel]/index.svelte src/routes/[city]/[hotel]/room/[slug].svelte src/routes/[city]/[hotel]/search.svelte src/routes/[city]/index.svelte src/routes/_error.svelte src/routes/_layout.svelte src/routes/contacto.svelte src/routes/eventos.svelte src/routes/index.svelte src/routes/promos/[slug].svelte src/routes/reservation/booknow.svelte src/routes/reservation/debug.svelte src/routes/reservation/email.svelte src/routes/reservation/review.svelte
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at /Users/josesachs/sapper-proj/node_modules/svelte-i18n/dist/cli.js:17:3905
    at async Command.<anonymous> (/Users/josesachs/sapper-proj/node_modules/svelte-i18n/dist/cli.js:17:3881)
```

</details>

**Information about your project:**

- Your browser and the version: Chrome 79.0.3945

- Your operating system: macOS Mojave 10.14.5

- `svelte-i18n` version 2.3.0

- Using Rollup

**Comment by kaisermann** [comment]
Hey 👋 does it occur for a single file? If not, would you be able to pin point the offending one and post its content?

**Comment by jhewt** [comment]
Nevermind, user error! I had to execute like this:

```yarn run svelte-i18n extract "src/**/*.svelte"```

Apparently, each file path was being autocompleted as a unique param for each file, so the CLI was receiving like 200 params instead of 2 or 3.
I'm not sure if this is a behaviour introduced by executing it from yarn or my shell (zsh).

Thanks for replying!
