### ISSUE TITLE
Tests are failing when running when OS using US date/time formatting

### ISSUE THREAD

**Issue by Jerome1337** [kaisermann/svelte-i18n#96]
**Describe the bug**
Tests are failing when running when OS using US date/time formatting.
Tests ignore the given locale and return the date with the current OS date/time formatting option

**Logs**
```sh
~/Documents/Projects/svelte-i18n master* 18s ❯ npm run test

> svelte-i18n@3.1.0 pretest /home/jerome/Documents/Projects/svelte-i18n
> npm run build


> svelte-i18n@3.1.0 prebuild /home/jerome/Documents/Projects/svelte-i18n
> yarn clean

yarn run v1.22.5
$ rm -rf dist/ types/
Done in 0.09s.

> svelte-i18n@3.1.0 build /home/jerome/Documents/Projects/svelte-i18n
> rollup -c


src/runtime/index.ts → dist/runtime.esm.js, dist/runtime.cjs.js...
(!) Circular dependencies
src/runtime/stores/locale.ts -> src/runtime/includes/loaderQueue.ts -> src/runtime/stores/dictionary.ts -> src/runtime/stores/locale.ts
src/runtime/stores/locale.ts -> src/runtime/includes/loaderQueue.ts -> src/runtime/stores/locale.ts
src/runtime/stores/locale.ts -> src/runtime/configs.ts -> src/runtime/stores/locale.ts
created dist/runtime.esm.js, dist/runtime.cjs.js in 2.8s

src/cli/index.ts → dist/cli.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
svelte/compiler (imported by src/cli/index.ts, src/cli/extract.ts)
created dist/cli.js in 1.6s

> svelte-i18n@3.1.0 postbuild /home/jerome/Documents/Projects/svelte-i18n
> yarn build:types

yarn run v1.22.5
$ tsc -p src/runtime --emitDeclarationOnly
Done in 2.91s.

> svelte-i18n@3.1.0 test /home/jerome/Documents/Projects/svelte-i18n
> jest

 PASS  test/cli/extract.test.ts
 PASS  test/runtime/stores/dictionary.test.ts
 PASS  test/runtime/includes/utils.test.ts
 PASS  test/runtime/includes/loaderQueue.test.ts
 PASS  test/runtime/includes/lookup.test.ts
 PASS  test/cli/includes.test.ts
 PASS  test/runtime/configs.test.ts
 PASS  test/runtime/stores/formatters.test.ts (7.048 s)
  ● Console

    console.warn
      [svelte-i18n] The message "missing" was not found in "en".

      47 |     if (getOptions().warnOnMissingMessages) {
      48 |       // istanbul ignore next
    > 49 |       console.warn(
         |               ^
      50 |         `[svelte-i18n] The message "${id}" was not found in "${getRelatedLocalesOf(
      51 |           locale,
      52 |         ).join('", "')}".${

      at formatMessage (src/runtime/stores/formatters.ts:49:15)
      at Object.<anonymous> (test/runtime/stores/formatters.test.ts:76:10)

 PASS  test/runtime/index.test.ts (6.812 s)
 FAIL  test/runtime/includes/formatters.test.ts (7.048 s)
  ● number formatter › formats a number according to a locale

    expect(received).toBe(expected) // Object.is equality

    Expected: "123.123"
    Received: "123,123"

      28 |   it('formats a number according to a locale', () => {
      29 |     init({ fallbackLocale: 'en' });
    > 30 |     expect(getNumberFormatter({ locale: 'pt-BR' }).format(number)).toBe(
         |                                                                    ^
      31 |       '123.123',
      32 |     );
      33 |   });

      at Object.<anonymous> (test/runtime/includes/formatters.test.ts:30:68)

  ● number formatter › formats a number according to the currently set locale

    expect(received).toBe(expected) // Object.is equality

    Expected: "123.123"
    Received: "123,123"

      57 |
      58 |     locale.set('nl');
    > 59 |     expect(getNumberFormatter().format(number)).toBe('123.123');
         |                                                 ^
      60 |   });
      61 | });
      62 |

      at Object.<anonymous> (test/runtime/includes/formatters.test.ts:59:49)

  ● date formatter › formats a date according to a locale

    expect(received).toBe(expected) // Object.is equality

    Expected: "01/02/19"
    Received: "2/1/19"

      76 |
      77 |   it('formats a date according to a locale', () => {
    > 78 |     expect(getDateFormatter({ locale: 'pt-BR' }).format(date)).toBe('01/02/19');
         |                                                                ^
      79 |   });
      80 |
      81 |   it('throws if passed a non-existing format', () => {

      at Object.<anonymous> (test/runtime/includes/formatters.test.ts:78:64)

  ● date formatter › formats a date according to the currently set locale

    expect(received).toBe(expected) // Object.is equality

    Expected: "1-2-19"
    Received: "2/1/19"

      114 |
      115 |     locale.set('nl');
    > 116 |     expect(getDateFormatter().format(date)).toBe('1-2-19');
          |                                             ^
      117 |   });
      118 | });
      119 |

      at Object.<anonymous> (test/runtime/includes/formatters.test.ts:116:45)

  ● time formatter › formats a time according to a locale

    expect(received).toBe(expected) // Object.is equality

    Expected: "20:37"
    Received: "8:37 PM"

      133 |
      134 |   it('formats a time according to a locale', () => {
    > 135 |     expect(getTimeFormatter({ locale: 'pt-BR' }).format(time)).toBe('20:37');
          |                                                                ^
      136 |   });
      137 |
      138 |   it('formats a time with a custom format', () => {

      at Object.<anonymous> (test/runtime/includes/formatters.test.ts:135:64)

  ● time formatter › formats time according to the currently set locale

    expect(received).toBe(expected) // Object.is equality

    Expected: "20:37"
    Received: "8:37 PM"

      175 |
      176 |     locale.set('nl');
    > 177 |     expect(getTimeFormatter().format(time)).toBe('20:37');
          |                                             ^
      178 |   });
      179 | });
      180 |

      at Object.<anonymous> (test/runtime/includes/formatters.test.ts:177:45)

 PASS  test/runtime/stores/locale.test.ts (7.046 s)
--------------------------|---------|----------|---------|---------|-------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
--------------------------|---------|----------|---------|---------|-------------------
All files                 |   91.49 |    86.84 |   81.95 |   91.82 |
 cli                      |   69.77 |    77.33 |      70 |   70.34 |
  extract.ts              |    98.9 |    93.55 |     100 |   98.81 | 40
  index.ts                |       0 |        0 |       0 |       0 | 1-78
 cli/includes             |     100 |    91.67 |     100 |     100 |
  deepGet.ts              |     100 |      100 |     100 |     100 |
  deepSet.ts              |     100 |      100 |     100 |     100 |
  getObjFromExpression.ts |     100 |       75 |     100 |     100 | 9
 runtime                  |     100 |    76.92 |   46.15 |     100 |
  configs.ts              |     100 |       70 |     100 |     100 | 62-70
  index.ts                |     100 |      100 |   41.67 |     100 |
 runtime/includes         |   99.38 |    92.11 |     100 |     100 |
  flatObj.ts              |     100 |      100 |     100 |     100 |
  formatters.ts           |     100 |      100 |     100 |     100 |
  loaderQueue.ts          |     100 |    90.48 |     100 |     100 | 25,95
  localeGetters.ts        |     100 |    71.43 |     100 |     100 | 18-39
  lookup.ts               |      96 |     87.5 |     100 |     100 | 7,9
  memoize.ts              |     100 |      100 |     100 |     100 |
 runtime/stores           |   99.12 |    94.23 |   96.55 |   99.04 |
  dictionary.ts           |     100 |    91.67 |     100 |     100 | 11
  formatters.ts           |     100 |    92.86 |     100 |     100 | 47
  loading.ts              |     100 |      100 |     100 |     100 |
  locale.ts               |   97.78 |    96.15 |   90.91 |   97.73 | 79
--------------------------|---------|----------|---------|---------|-------------------

Test Suites: 1 failed, 10 passed, 11 total
Tests:       6 failed, 103 passed, 109 total
Snapshots:   1 passed, 1 total
Time:        10.736 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-i18n@3.1.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-i18n@3.1.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jerome/.npm/_logs/2020-09-25T10_28_26_017Z-debug.log
```

**To Reproduce**
Change your OS date/time configuration to US formatting (12 hours clock + `mm/dd/YYYY` date format).

My date config
```sh
~/Documents/Projects/svelte-i18n master* ❯ date
Fri 25 Sep 2020 12:32:34 PM CEST

~/Documents/Projects/svelte-i18n master* ❯ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Then run tests with `npm run test`

**Expected behavior**
Every tests should be passing.

**Stacktraces**
Nothing

**Information about your project:**

- Your browser and the version: Not using browser

- Your operating system: Ubuntu 20.04

- `svelte-i18n` version: latest/master

- Using Rollup

**Additional context**
Nothing

**Comment by kaisermann** [comment]
Hey, @Jerome1337 👋 

Can you try again after pulling from the current main branch?

**Comment by Jerome1337** [comment]
Hi @kaisermann 

All tests passed now.
